{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "571bf1aa",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import gradio as gr\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.ensemble import RandomForestClassifier"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "7ca83818",
   "metadata": {},
   "outputs": [],
   "source": [
    "tracks_clean = pd.read_csv('./data/tracks_clean.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "52de77ba",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>popularity</th>\n",
       "      <th>duration_ms</th>\n",
       "      <th>explicit</th>\n",
       "      <th>release_date</th>\n",
       "      <th>danceability</th>\n",
       "      <th>energy</th>\n",
       "      <th>key</th>\n",
       "      <th>loudness</th>\n",
       "      <th>mode</th>\n",
       "      <th>speechiness</th>\n",
       "      <th>acousticness</th>\n",
       "      <th>instrumentalness</th>\n",
       "      <th>liveness</th>\n",
       "      <th>valence</th>\n",
       "      <th>tempo</th>\n",
       "      <th>time_signature</th>\n",
       "      <th>popularity_category</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>6</td>\n",
       "      <td>126903</td>\n",
       "      <td>0</td>\n",
       "      <td>1922-02-22</td>\n",
       "      <td>0.645</td>\n",
       "      <td>0.4450</td>\n",
       "      <td>0</td>\n",
       "      <td>-13.338</td>\n",
       "      <td>1</td>\n",
       "      <td>0.4510</td>\n",
       "      <td>0.674</td>\n",
       "      <td>0.744000</td>\n",
       "      <td>0.1510</td>\n",
       "      <td>0.1270</td>\n",
       "      <td>104.851</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>0</td>\n",
       "      <td>98200</td>\n",
       "      <td>0</td>\n",
       "      <td>1922-06-01</td>\n",
       "      <td>0.695</td>\n",
       "      <td>0.2630</td>\n",
       "      <td>0</td>\n",
       "      <td>-22.136</td>\n",
       "      <td>1</td>\n",
       "      <td>0.9570</td>\n",
       "      <td>0.797</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.1480</td>\n",
       "      <td>0.6550</td>\n",
       "      <td>102.009</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>0</td>\n",
       "      <td>181640</td>\n",
       "      <td>0</td>\n",
       "      <td>1922-03-21</td>\n",
       "      <td>0.434</td>\n",
       "      <td>0.1770</td>\n",
       "      <td>1</td>\n",
       "      <td>-21.180</td>\n",
       "      <td>1</td>\n",
       "      <td>0.0512</td>\n",
       "      <td>0.994</td>\n",
       "      <td>0.021800</td>\n",
       "      <td>0.2120</td>\n",
       "      <td>0.4570</td>\n",
       "      <td>130.418</td>\n",
       "      <td>5</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>0</td>\n",
       "      <td>176907</td>\n",
       "      <td>0</td>\n",
       "      <td>1922-03-21</td>\n",
       "      <td>0.321</td>\n",
       "      <td>0.0946</td>\n",
       "      <td>7</td>\n",
       "      <td>-27.961</td>\n",
       "      <td>1</td>\n",
       "      <td>0.0504</td>\n",
       "      <td>0.995</td>\n",
       "      <td>0.918000</td>\n",
       "      <td>0.1040</td>\n",
       "      <td>0.3970</td>\n",
       "      <td>169.980</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>0</td>\n",
       "      <td>163080</td>\n",
       "      <td>0</td>\n",
       "      <td>1922-01-01</td>\n",
       "      <td>0.402</td>\n",
       "      <td>0.1580</td>\n",
       "      <td>3</td>\n",
       "      <td>-16.900</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0390</td>\n",
       "      <td>0.989</td>\n",
       "      <td>0.130000</td>\n",
       "      <td>0.3110</td>\n",
       "      <td>0.1960</td>\n",
       "      <td>103.220</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>586596</th>\n",
       "      <td>50</td>\n",
       "      <td>258267</td>\n",
       "      <td>0</td>\n",
       "      <td>2020-09-26</td>\n",
       "      <td>0.560</td>\n",
       "      <td>0.5180</td>\n",
       "      <td>0</td>\n",
       "      <td>-7.471</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0292</td>\n",
       "      <td>0.785</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.0648</td>\n",
       "      <td>0.2110</td>\n",
       "      <td>131.896</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>586597</th>\n",
       "      <td>72</td>\n",
       "      <td>153293</td>\n",
       "      <td>0</td>\n",
       "      <td>2020-10-21</td>\n",
       "      <td>0.765</td>\n",
       "      <td>0.6630</td>\n",
       "      <td>0</td>\n",
       "      <td>-5.223</td>\n",
       "      <td>1</td>\n",
       "      <td>0.0652</td>\n",
       "      <td>0.141</td>\n",
       "      <td>0.000297</td>\n",
       "      <td>0.0924</td>\n",
       "      <td>0.6860</td>\n",
       "      <td>150.091</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>586598</th>\n",
       "      <td>70</td>\n",
       "      <td>187601</td>\n",
       "      <td>0</td>\n",
       "      <td>2020-09-02</td>\n",
       "      <td>0.535</td>\n",
       "      <td>0.3140</td>\n",
       "      <td>7</td>\n",
       "      <td>-12.823</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0408</td>\n",
       "      <td>0.895</td>\n",
       "      <td>0.000150</td>\n",
       "      <td>0.0874</td>\n",
       "      <td>0.0663</td>\n",
       "      <td>145.095</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>586599</th>\n",
       "      <td>58</td>\n",
       "      <td>142003</td>\n",
       "      <td>0</td>\n",
       "      <td>2021-03-05</td>\n",
       "      <td>0.696</td>\n",
       "      <td>0.6150</td>\n",
       "      <td>10</td>\n",
       "      <td>-6.212</td>\n",
       "      <td>1</td>\n",
       "      <td>0.0345</td>\n",
       "      <td>0.206</td>\n",
       "      <td>0.000003</td>\n",
       "      <td>0.3050</td>\n",
       "      <td>0.4380</td>\n",
       "      <td>90.029</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>586600</th>\n",
       "      <td>38</td>\n",
       "      <td>214360</td>\n",
       "      <td>0</td>\n",
       "      <td>2015-07-01</td>\n",
       "      <td>0.686</td>\n",
       "      <td>0.7230</td>\n",
       "      <td>6</td>\n",
       "      <td>-7.067</td>\n",
       "      <td>1</td>\n",
       "      <td>0.0363</td>\n",
       "      <td>0.105</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.2640</td>\n",
       "      <td>0.9750</td>\n",
       "      <td>112.204</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>586601 rows Ã— 17 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        popularity  duration_ms  explicit release_date  danceability  energy  \\\n",
       "0                6       126903         0   1922-02-22         0.645  0.4450   \n",
       "1                0        98200         0   1922-06-01         0.695  0.2630   \n",
       "2                0       181640         0   1922-03-21         0.434  0.1770   \n",
       "3                0       176907         0   1922-03-21         0.321  0.0946   \n",
       "4                0       163080         0   1922-01-01         0.402  0.1580   \n",
       "...            ...          ...       ...          ...           ...     ...   \n",
       "586596          50       258267         0   2020-09-26         0.560  0.5180   \n",
       "586597          72       153293         0   2020-10-21         0.765  0.6630   \n",
       "586598          70       187601         0   2020-09-02         0.535  0.3140   \n",
       "586599          58       142003         0   2021-03-05         0.696  0.6150   \n",
       "586600          38       214360         0   2015-07-01         0.686  0.7230   \n",
       "\n",
       "        key  loudness  mode  speechiness  acousticness  instrumentalness  \\\n",
       "0         0   -13.338     1       0.4510         0.674          0.744000   \n",
       "1         0   -22.136     1       0.9570         0.797          0.000000   \n",
       "2         1   -21.180     1       0.0512         0.994          0.021800   \n",
       "3         7   -27.961     1       0.0504         0.995          0.918000   \n",
       "4         3   -16.900     0       0.0390         0.989          0.130000   \n",
       "...     ...       ...   ...          ...           ...               ...   \n",
       "586596    0    -7.471     0       0.0292         0.785          0.000000   \n",
       "586597    0    -5.223     1       0.0652         0.141          0.000297   \n",
       "586598    7   -12.823     0       0.0408         0.895          0.000150   \n",
       "586599   10    -6.212     1       0.0345         0.206          0.000003   \n",
       "586600    6    -7.067     1       0.0363         0.105          0.000000   \n",
       "\n",
       "        liveness  valence    tempo  time_signature  popularity_category  \n",
       "0         0.1510   0.1270  104.851               3                    1  \n",
       "1         0.1480   0.6550  102.009               1                    0  \n",
       "2         0.2120   0.4570  130.418               5                    0  \n",
       "3         0.1040   0.3970  169.980               3                    0  \n",
       "4         0.3110   0.1960  103.220               4                    0  \n",
       "...          ...      ...      ...             ...                  ...  \n",
       "586596    0.0648   0.2110  131.896               4                    1  \n",
       "586597    0.0924   0.6860  150.091               4                    1  \n",
       "586598    0.0874   0.0663  145.095               4                    1  \n",
       "586599    0.3050   0.4380   90.029               4                    1  \n",
       "586600    0.2640   0.9750  112.204               4                    1  \n",
       "\n",
       "[586601 rows x 17 columns]"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "tracks_clean"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "8f6ae9c8",
   "metadata": {},
   "outputs": [],
   "source": [
    "X = tracks_clean.drop(columns=['popularity', 'duration_ms', 'release_date', 'key', 'mode', 'speechiness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature', 'popularity_category'], axis=1)\n",
    "y = tracks_clean['popularity_category']\n",
    "\n",
    "#test/train/split\n",
    "X_train, X_test, y_train, y_test = train_test_split(X,\n",
    "                                                    y,\n",
    "                                                    test_size=0.23,\n",
    "                                                    random_state=42,\n",
    "                                                    stratify=y\n",
    "                                                   )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "b4b3939e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>#sk-container-id-1 {color: black;background-color: white;}#sk-container-id-1 pre{padding: 0;}#sk-container-id-1 div.sk-toggleable {background-color: white;}#sk-container-id-1 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-1 label.sk-toggleable__label-arrow:before {content: \"â–¸\";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-1 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-1 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-1 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: \"â–¾\";}#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-1 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-1 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-1 div.sk-parallel-item::after {content: \"\";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-serial::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-1 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-1 div.sk-item {position: relative;z-index: 1;}#sk-container-id-1 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-1 div.sk-item::before, #sk-container-id-1 div.sk-parallel-item::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-1 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-1 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-1 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-1 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-1 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-1 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-1 div.sk-label-container {text-align: center;}#sk-container-id-1 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-1 div.sk-text-repr-fallback {display: none;}</style><div id=\"sk-container-id-1\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>RandomForestClassifier()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-1\" type=\"checkbox\" checked><label for=\"sk-estimator-id-1\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">RandomForestClassifier</label><div class=\"sk-toggleable__content\"><pre>RandomForestClassifier()</pre></div></div></div></div></div>"
      ],
      "text/plain": [
       "RandomForestClassifier()"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "rf = RandomForestClassifier()\n",
    "rf.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "6b523cc4",
   "metadata": {},
   "outputs": [],
   "source": [
    "def predict_popularity(explicit, danceability, energy, loudness, acousticness):\n",
    "    tracks = pd.DataFrame.from_dict({'explicit':[explicit],\n",
    "                                     'danceability':[danceability],\n",
    "                                     'energy':[energy],\n",
    "                                     'loudness':[loudness],\n",
    "                                     'acousticness':[acousticness]})\n",
    "    \n",
    "    predict = rf.predict_proba(tracks)[0]\n",
    "    \n",
    "    return {rf.classes_[i]: predict[i] for i in range(3)}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "74547ee9",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running on local URL:  http://127.0.0.1:7860/\n",
      "\n",
      "To create a public link, set `share=True` in `launch()`.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"http://127.0.0.1:7860/\" width=\"900\" height=\"500\" allow=\"autoplay; camera; microphone;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/routes.py\", line 255, in run_predict\n",
      "    output = await app.blocks.process_api(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 630, in process_api\n",
      "    predictions, duration = await self.call_function(fn_index, processed_input)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/blocks.py\", line 545, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/to_thread.py\", line 28, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 818, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py\", line 754, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 489, in <lambda>\n",
      "    lambda *args: self.run_prediction(args)[0]\n",
      "  File \"/Users/josedelgadillo/opt/anaconda3/envs/dsi/lib/python3.9/site-packages/gradio/interface.py\", line 669, in run_prediction\n",
      "    prediction = self.fn(*processed_input)\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in predict_popularity\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "  File \"/var/folders/6t/85msmsnj1ksb3tpnsplp1bc00000gn/T/ipykernel_42272/1533585298.py\", line 10, in <dictcomp>\n",
      "    return {rf.classes_[i]: predict[i] for i in range(3)}\n",
      "IndexError: index 2 is out of bounds for axis 0 with size 2\n"
     ]
    }
   ],
   "source": [
    "explicit = gr.components.Slider(minimum=0, maximum=1, label='explicit')\n",
    "\n",
    "danceability = gr.components.Slider(minimum=0, maximum=1, label='danceability')\n",
    "\n",
    "energy = gr.components.Slider(minimum=0, maximum=1, label='energy')\n",
    "\n",
    "loudness = gr.components.Slider(minimum=-60, maximum=5.376, label='loudness')\n",
    "\n",
    "acousticness = gr.components.Slider(minimum=0, maximum=1, label='acousticness')\n",
    "\n",
    "gr.Interface(predict_popularity, [explicit, danceability, energy, loudness, acousticness],\n",
    "            'label', live=True, interpretation='default').launch(debug=True)\n",
    "\n",
    "#https://towardsdatascience.com/understanding-feature-importance-and-how-to-implement-it-in-python-ff0287b20285"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "383c59e6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
